# Generated by Django 2.2.7 on 2019-12-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
