# Generated by Django 2.2.7 on 2019-12-11 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_auto_20191211_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
