# Generated by Django 2.2.7 on 2019-12-13 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_animals_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2989a3c4-1d77-11ea-a8c3-f01898ed9769'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=160),
        ),
    ]
